### ISSUE TITLE
User name

### ISSUE THREAD

**Issue by ASShestak** [Robinamixan/Drupal7_MinstakesReports#2]
https://github.com/Robinamixan/Drupal7_MinstakesReports/blob/62566f4dbf65e1157dd9cd4c1adfb5a94789c4dd/sites/all/modules/text_mistakes_reports/text_mistakes_reports.install#L39

It should be uid, not name. 
On site can be several users with the same name.

**Comment by Robinamixan** [comment]
fixed

**Comment by Robinamixan** [comment]
fixed
