### ISSUE TITLE
Use DrupalDefaultEntityController

### ISSUE THREAD

**Issue by ASShestak** [Robinamixan/Drupal7_MinstakesReports#22]
https://github.com/Robinamixan/Drupal7_MinstakesReports/blob/729c95a70d8008d27c508e5f99d88b2546642a63/sites/all/modules/text_mistakes_reports/text_mistakes_reports_entity_controller.inc#L3

Do not implement DrupalEntityControllerInterface, use DrupalDefaultEntityController.
So you do need write all methods.
Please rewrite entity controller.

**Comment by Robinamixan** [comment]
fixed
