### ISSUE TITLE
It should be int. Add foreign key to user table.

### ISSUE THREAD

**Issue by ASShestak** [Robinamixan/Drupal7_MinstakesReports#24]
https://github.com/Robinamixan/Drupal7_MinstakesReports/blob/729c95a70d8008d27c508e5f99d88b2546642a63/sites/all/modules/text_mistakes_reports/text_mistakes_reports.install#L45

**Comment by Robinamixan** [comment]
int fixed, foreign keys "For documentation purposes only; foreign keys are not created in the database."
