### ISSUE TITLE
Write more pretty

### ISSUE THREAD

**Issue by ASShestak** [Robinamixan/Drupal7_MinstakesReports#26]
https://github.com/Robinamixan/Drupal7_MinstakesReports/blob/729c95a70d8008d27c508e5f99d88b2546642a63/sites/all/modules/text_mistakes_reports/text_mistakes_reports.module#L12
For example:
$message = 'A module that add popup to field types "long text" and "long text and summary"'  . 
                    ' and it can send reports about mistakes to admin email.';
  switch ($path) {
    case 'admin/help#text_mistakes_reports':
      return t(message );
      break;
  }

**Comment by Robinamixan** [comment]
understood, fixed
