### ISSUE TITLE
Change field name

### ISSUE THREAD

**Issue by ASShestak** [Robinamixan/Drupal7_MinstakesReports#5]
https://github.com/Robinamixan/Drupal7_MinstakesReports/blob/62566f4dbf65e1157dd9cd4c1adfb5a94789c4dd/sites/all/modules/text_mistakes_reports/text_mistakes_reports.install#L45

Can you change 'user_ip' to 'ip' because anonymous users also can submit issues.

**Comment by Robinamixan** [comment]
continue to use 'user_ip', because anonymous is type of users
